# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-15 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritePrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['printer__server_name', 'printer__name'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=255, verbose_name=b'Server')),
                ('server_name', models.CharField(max_length=255, verbose_name=b'Server Name')),
                ('name', models.CharField(max_length=255, verbose_name=b'Printer')),
                ('info', models.CharField(max_length=255, verbose_name=b'Description')),
                ('location', models.CharField(max_length=255, verbose_name=b'Location')),
            ],
            options={
                'ordering': ['server_name', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='printer',
            unique_together=set([('server', 'name')]),
        ),
        migrations.AddField(
            model_name='favouriteprinter',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_cups.Printer'),
        ),
        migrations.AddField(
            model_name='favouriteprinter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favouriteprinter',
            unique_together=set([('user', 'printer')]),
        ),
    ]
